#!/usr/bin/env python3
"""
Batch calibration helper for GestureLab mouth/raise action thresholds.

Input: GestureLab CSV records generated by GestureDataRecorder.
Output: JSON + Markdown summary with recommended thresholds.
"""

from __future__ import annotations

import argparse
import csv
import dataclasses
import datetime as dt
import json
import math
import os
from pathlib import Path
from statistics import median
from typing import Iterable


@dataclasses.dataclass
class ImuRow:
    t: dt.datetime
    roll: float
    pitch: float
    yaw: float
    gx: float
    gy: float
    gz: float

    @property
    def pitch_abs(self) -> float:
        return abs(self.pitch)

    @property
    def roll_abs(self) -> float:
        return abs(self.roll)

    @property
    def gyro_mag(self) -> float:
        return math.sqrt((self.gx * self.gx) + (self.gy * self.gy) + (self.gz * self.gz))


@dataclasses.dataclass
class MarkerRow:
    t: dt.datetime
    note: str


@dataclasses.dataclass
class MarkerFeature:
    file: str
    marker_time: str
    note: str
    steady_pitch_abs_p10: float
    steady_pitch_abs_p90: float
    steady_roll_abs_p90: float
    steady_gyro_p90: float
    move_gyro_peak: float
    pre_gyro_peak: float
    stable_streak_seconds: float


def parse_iso8601(text: str) -> dt.datetime:
    return dt.datetime.fromisoformat(text.replace("Z", "+00:00"))


def safe_float(text: str) -> float | None:
    if text is None:
        return None
    text = text.strip()
    if not text:
        return None
    try:
        return float(text)
    except ValueError:
        return None


def quantile(values: list[float], q: float) -> float:
    if not values:
        return 0.0
    if q <= 0:
        return min(values)
    if q >= 1:
        return max(values)
    ordered = sorted(values)
    idx = (len(ordered) - 1) * q
    lo = int(math.floor(idx))
    hi = int(math.ceil(idx))
    if lo == hi:
        return ordered[lo]
    frac = idx - lo
    return ordered[lo] * (1.0 - frac) + ordered[hi] * frac


def read_record(csv_path: Path) -> tuple[list[ImuRow], list[MarkerRow]]:
    imu_rows: list[ImuRow] = []
    marker_rows: list[MarkerRow] = []

    with csv_path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            event = (row.get("event") or "").strip().upper()
            utc_time = row.get("utc_time") or ""
            if not utc_time:
                continue

            t = parse_iso8601(utc_time)

            if event == "MARK":
                marker_rows.append(MarkerRow(t=t, note=(row.get("note") or "").strip()))
                continue

            if event != "IMU":
                continue

            roll = safe_float(row.get("roll", ""))
            pitch = safe_float(row.get("pitch", ""))
            yaw = safe_float(row.get("yaw", ""))
            gx = safe_float(row.get("gx", ""))
            gy = safe_float(row.get("gy", ""))
            gz = safe_float(row.get("gz", ""))
            if None in (roll, pitch, yaw, gx, gy, gz):
                continue

            imu_rows.append(ImuRow(t=t, roll=roll or 0.0, pitch=pitch or 0.0, yaw=yaw or 0.0, gx=gx or 0.0, gy=gy or 0.0, gz=gz or 0.0))

    imu_rows.sort(key=lambda x: x.t)
    marker_rows.sort(key=lambda x: x.t)
    return imu_rows, marker_rows


def select_window(rows: list[ImuRow], start: dt.datetime, end: dt.datetime) -> list[ImuRow]:
    return [r for r in rows if start <= r.t <= end]


def stable_streak_seconds(
    rows: list[ImuRow],
    marker_time: dt.datetime,
    still_gyro: float,
    pitch_min: float,
    pitch_max: float,
    roll_max: float,
    max_back_seconds: float = 1.0,
) -> float:
    if not rows:
        return 0.0

    floor_t = marker_time - dt.timedelta(seconds=max_back_seconds)
    subset = [r for r in rows if floor_t <= r.t <= marker_time]
    if not subset:
        return 0.0

    subset.sort(key=lambda x: x.t)
    end = subset[-1].t
    start = end

    for i in range(len(subset) - 1, -1, -1):
        r = subset[i]
        pose_ok = pitch_min <= r.pitch_abs <= pitch_max and r.roll_abs <= roll_max
        if not pose_ok or r.gyro_mag > still_gyro:
            break
        if i < len(subset) - 1:
            gap = (subset[i + 1].t - r.t).total_seconds()
            if gap > 0.09:
                break
        start = r.t

    return max(0.0, (end - start).total_seconds())


def extract_features_for_marker(
    file_name: str,
    rows: list[ImuRow],
    marker: MarkerRow,
    marker_name: str,
) -> MarkerFeature | None:
    if marker.note != marker_name:
        return None

    t = marker.t
    steady = select_window(rows, t - dt.timedelta(seconds=0.45), t - dt.timedelta(seconds=0.05))
    move = select_window(rows, t - dt.timedelta(seconds=1.2), t - dt.timedelta(seconds=0.45))
    pre = select_window(rows, t - dt.timedelta(seconds=1.2), t)

    if len(steady) < 6 or len(move) < 6:
        return None

    steady_pitch_abs = [r.pitch_abs for r in steady]
    steady_roll_abs = [r.roll_abs for r in steady]
    steady_gyro = [r.gyro_mag for r in steady]
    move_gyro = [r.gyro_mag for r in move]
    pre_gyro = [r.gyro_mag for r in pre]

    return MarkerFeature(
        file=file_name,
        marker_time=t.isoformat(),
        note=marker.note,
        steady_pitch_abs_p10=quantile(steady_pitch_abs, 0.10),
        steady_pitch_abs_p90=quantile(steady_pitch_abs, 0.90),
        steady_roll_abs_p90=quantile(steady_roll_abs, 0.90),
        steady_gyro_p90=quantile(steady_gyro, 0.90),
        move_gyro_peak=max(move_gyro) if move_gyro else 0.0,
        pre_gyro_peak=max(pre_gyro) if pre_gyro else 0.0,
        stable_streak_seconds=0.0,
    )


def gather_features(record_paths: Iterable[Path], marker_name: str) -> list[MarkerFeature]:
    features: list[MarkerFeature] = []
    for path in record_paths:
        imu_rows, marker_rows = read_record(path)
        if not imu_rows or not marker_rows:
            continue

        for m in marker_rows:
            feat = extract_features_for_marker(path.name, imu_rows, m, marker_name)
            if feat is not None:
                features.append(feat)

    return features


def recommend_thresholds(features: list[MarkerFeature]) -> dict[str, float]:
    if not features:
        return {
            "MoveStartGyroThreshold": 900.0,
            "StillGyroThreshold": 450.0,
            "HoldBreakGyroThreshold": 1400.0,
            "PosePitchAbsMin": 24.0,
            "PosePitchAbsMax": 88.0,
            "PoseRollAbsMax": 86.0,
            "HoldSeconds": 0.30,
            "CooldownSeconds": 1.20,
        }

    pitch_low = [f.steady_pitch_abs_p10 for f in features]
    pitch_high = [f.steady_pitch_abs_p90 for f in features]
    roll_high = [f.steady_roll_abs_p90 for f in features]
    still_gyro = [f.steady_gyro_p90 for f in features]
    move_peak = [f.move_gyro_peak for f in features]
    pre_peak = [f.pre_gyro_peak for f in features]

    pose_pitch_abs_min = max(8.0, round(quantile(pitch_low, 0.10) - 2.0, 1))
    pose_pitch_abs_max = min(89.0, round(quantile(pitch_high, 0.95) + 4.0, 1))
    pose_roll_abs_max = min(89.0, round(quantile(roll_high, 0.95) + 4.0, 1))

    still_gyro_threshold = max(120.0, round(quantile(still_gyro, 0.90) * 1.10, 1))
    move_start_candidate = round(quantile(move_peak, 0.25), 1)
    move_start_gyro_threshold = max(move_start_candidate, round(still_gyro_threshold * 1.7, 1))

    hold_break_candidate = round(quantile(pre_peak, 0.95), 1)
    hold_break_gyro_threshold = max(hold_break_candidate, round(move_start_gyro_threshold * 1.5, 1))

    provisional = {
        "MoveStartGyroThreshold": move_start_gyro_threshold,
        "StillGyroThreshold": still_gyro_threshold,
        "HoldBreakGyroThreshold": hold_break_gyro_threshold,
        "PosePitchAbsMin": pose_pitch_abs_min,
        "PosePitchAbsMax": pose_pitch_abs_max,
        "PoseRollAbsMax": pose_roll_abs_max,
    }

    stable_streaks = [f.stable_streak_seconds for f in features if f.stable_streak_seconds > 0]
    if stable_streaks:
        hold_seconds = max(0.20, min(0.55, round(quantile(stable_streaks, 0.50), 2)))
    else:
        hold_seconds = 0.30

    cooldown_seconds = max(0.60, min(2.00, round(max(1.2, hold_seconds * 3.5), 2)))

    provisional["HoldSeconds"] = hold_seconds
    provisional["CooldownSeconds"] = cooldown_seconds
    return provisional


def enrich_stable_streaks(record_paths: Iterable[Path], marker_name: str, features: list[MarkerFeature], thresholds: dict[str, float]) -> None:
    key = {(f.file, f.marker_time): f for f in features}

    for path in record_paths:
        imu_rows, marker_rows = read_record(path)
        if not imu_rows or not marker_rows:
            continue

        for m in marker_rows:
            if m.note != marker_name:
                continue
            marker_key = (path.name, m.t.isoformat())
            feat = key.get(marker_key)
            if feat is None:
                continue

            feat.stable_streak_seconds = stable_streak_seconds(
                imu_rows,
                m.t,
                still_gyro=thresholds["StillGyroThreshold"],
                pitch_min=thresholds["PosePitchAbsMin"],
                pitch_max=thresholds["PosePitchAbsMax"],
                roll_max=thresholds["PoseRollAbsMax"],
            )


def write_outputs(
    output_dir: Path,
    marker_name: str,
    features: list[MarkerFeature],
    thresholds: dict[str, float],
    source_files: list[Path],
) -> tuple[Path, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)

    payload = {
        "generated_at_utc": dt.datetime.now(dt.timezone.utc).isoformat(),
        "marker_name": marker_name,
        "source_file_count": len(source_files),
        "matched_marker_count": len(features),
        "thresholds": thresholds,
        "features": [dataclasses.asdict(f) for f in features],
    }

    json_path = output_dir / f"mouth_calibration_{marker_name}.json"
    with json_path.open("w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)

    report_path = output_dir / f"mouth_calibration_{marker_name}.md"
    lines: list[str] = []
    lines.append("# GestureLab Mouth Calibration Report")
    lines.append("")
    lines.append(f"- Marker: `{marker_name}`")
    lines.append(f"- Source files: `{len(source_files)}`")
    lines.append(f"- Matched marker samples: `{len(features)}`")
    lines.append("")
    lines.append("## Recommended Thresholds")
    lines.append("")
    for k, v in thresholds.items():
        if isinstance(v, float):
            lines.append(f"- `{k}`: `{v:.2f}`")
        else:
            lines.append(f"- `{k}`: `{v}`")
    lines.append("")
    lines.append("## Suggested Constants Snippet")
    lines.append("")
    lines.append("```csharp")
    for k, v in thresholds.items():
        if isinstance(v, float):
            lines.append(f"private const double {k} = {v:.2f};")
        else:
            lines.append(f"private const double {k} = {v};")
    lines.append("```")
    lines.append("")
    lines.append("## Notes")
    lines.append("")
    lines.append("- `steady_*` features come from [marker-0.45s, marker-0.05s], representing the hold phase before trigger.")
    lines.append("- `move_gyro_peak` comes from [marker-1.2s, marker-0.45s], representing raise/move phase.")
    lines.append("- If matched samples are too few (< 20), collect more trials before adopting the thresholds.")

    with report_path.open("w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return json_path, report_path


def find_record_files(input_path: Path) -> list[Path]:
    if input_path.is_file() and input_path.suffix.lower() == ".csv":
        return [input_path]

    if input_path.is_dir():
        return sorted(input_path.rglob("*.csv"))

    return []


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Fit GestureLab mouth-action thresholds from recorded CSV sessions.")
    parser.add_argument(
        "--input",
        required=True,
        help="CSV file or folder containing GestureLab record CSVs.",
    )
    parser.add_argument(
        "--marker",
        default="MOUTH_HOLD",
        help="Marker note used as positive samples (default: MOUTH_HOLD).",
    )
    parser.add_argument(
        "--output",
        default="./calibration_output",
        help="Output folder for JSON/Markdown report.",
    )
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    input_path = Path(args.input).expanduser().resolve()
    output_dir = Path(args.output).expanduser().resolve()
    marker_name = args.marker.strip()

    record_files = find_record_files(input_path)
    if not record_files:
        print(f"No CSV files found under: {input_path}")
        return 1

    features = gather_features(record_files, marker_name)
    if not features:
        print(f"No matched marker samples for marker: {marker_name}")
        return 2

    first_pass = recommend_thresholds(features)
    enrich_stable_streaks(record_files, marker_name, features, first_pass)
    final_thresholds = recommend_thresholds(features)

    json_path, report_path = write_outputs(output_dir, marker_name, features, final_thresholds, record_files)

    print("Calibration completed.")
    print(f"- input files: {len(record_files)}")
    print(f"- matched samples: {len(features)}")
    print(f"- json: {json_path}")
    print(f"- report: {report_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
